In [1]:
import import_ipynb
import glassdoor_scraper as gs
import pandas as pd

# Need to use VPN to access US Glassdoor if out of country
path = "C:/Users/Visitor/Desktop/Github/Salary Estimate Project/chromedriver"
df = gs.get_jobs('data scientist', 15, False, path, 15)

importing Jupyter notebook from glassdoor_scraper.ipynb
x out worked
Progress: 0/15
Progress: 1/15
Progress: 2/15
Progress: 3/15
Progress: 4/15
Progress: 5/15
Progress: 6/15
Progress: 7/15
Progress: 8/15
Progress: 9/15
Progress: 10/15
Progress: 11/15
Progress: 12/15
Progress: 13/15
Progress: 14/15
Progress: 15/15

In [2]:
df.head(5)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Marketing Data Scientist,CA$58k-CA$90k (Glassdoor Est.),Top Hat is looking for a technical Marketing D...,3.5,Top Hat\n3.5,Toronto,-1,201 to 500 Employees,2009,Company - Private,Colleges & Universities,Education,$25 to $50 million (USD),-1
1,"Data Scientist, Fraud Analytics",CA$58k-CA$90k (Glassdoor Est.),Data Scientist Fraud Analytics\n\nFraud Manage...,3.6,Interac\n3.6,Toronto,-1,201 to 500 Employees,1984,Company - Private,Financial Transaction Processing,Finance,Unknown / Non-Applicable,-1
2,"Intern, Data Engineer – Digital Strategy and I...",CA$58k-CA$90k (Glassdoor Est.),EXPERIENCE THE EDGE\n\n\nWe’re one of Canada’s...,4.4,PSP Investments\n4.4,Montreal,-1,501 to 1000 Employees,1999,Other Organization,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1
3,"Data Analyst, NAV Recon",CA$58k-CA$90k (Glassdoor Est.),"Data Analyst, NAV Recon\nConnor, Clark & Lunn ...",4.3,"Connor, Clark & Lunn Financial Group\n4.3",Vancouver,-1,201 to 500 Employees,1982,Company - Private,Investment Banking & Asset Management,Finance,$25 to $50 million (USD),-1
4,Data Mining Specialist,CA$58k-CA$90k (Glassdoor Est.),"What we do\nInterested in solving problems, en...",5.0,Global Spatial Technology Solutions\n5.0,Dartmouth,-1,1 to 50 Employees,-1,Unknown,-1,-1,Less than $1 million (USD),-1

In [ ]:
df.info

In [ ]:
df.shape

In [ ]:
df.describe